---
engines:
  duplication:
    enabled: true
    config:
      languages:
        - javascript
  eslint:
    enabled: true
    channel: eslint-5
  fixme:
    enabled: true
ratings:
  paths:
    - '**.js'
exclude_paths:
  - node_modules/**/*
  - __tests__/**/*
  - __mocks__/**/*
