---
ls:
  .config.ts: camelCase | PascalCase
  .d.ts: camelCase | PascalCase
  .dir: kebab-case | regex:__[a-z]+__
  .md: lowercase | SCREAMING_SNAKE_CASE
  .nut.ts: camelCase | PascalCase
  .test.ts: camelCase | PascalCase
  .ts: camelCase | PascalCase

ignore: 
  - .claude
  - .git 
  - .github
  - .husky
  - .nyc_output
  - .stryker-tmp
  - .vscode
  - .idea
  - .wireit
  - e2e
  - lib
  - megalinter-reports
  - node_modules
  - reports