import type { Metadata } from '../types/metadata.js'

// Internal registry for metadata definitions not present in SDR
// or that need special handling different from SDR's structure
// Priority: internalRegistry > SDR > additionalMetadataRegistry

export default [
  // CustomLabel needs suffix even though it matches parent in SDR
  {
    directoryName: 'labels',
    inFolder: false,
    metaFile: false,
    parentXmlName: 'CustomLabels',
    xmlName: 'CustomLabel',
    childXmlNames: ['CustomLabel'],
    suffix: 'labels',
    xmlTag: 'labels',
    key: 'fullName',
  },
  // Child type for field translations within CustomObjectTranslation files.
  // Maps .fieldTranslation suffix to CustomObjectTranslation type.
  {
    directoryName: 'objectTranslations',
    inFolder: false,
    metaFile: false,
    parentXmlName: 'CustomObjectTranslation',
    suffix: 'fieldTranslation',
    xmlName: 'CustomObjectTranslation',
    xmlTag: 'fields',
    key: 'name',
    excluded: true,
  },
  // Overriding SDR CustomFieldTranslation to prevent it from matching 'fields' directory
  // and shadowing CustomField. We disable it effectively by giving it bogus directory/suffix.
  {
    xmlName: 'CustomFieldTranslation',
    directoryName: 'disabled_custom_field_translation',
    suffix: 'disabled_fieldTranslation',
    inFolder: false,
    metaFile: false,
    excluded: true,
  },
  // pruneOnly types - only handled for deletions (destructiveChanges)
  {
    directoryName: 'globalValueSetTranslations',
    inFolder: false,
    metaFile: false,
    suffix: 'globalValueSetTranslation',
    xmlName: 'GlobalValueSetTranslation',
    xmlTag: undefined,
    pruneOnly: true,
  },
  {
    directoryName: 'standardValueSetTranslations',
    inFolder: false,
    metaFile: false,
    suffix: 'standardValueSetTranslation',
    xmlName: 'StandardValueSetTranslation',
    xmlTag: undefined,
    pruneOnly: true,
  },
  {
    directoryName: 'profiles',
    inFolder: false,
    metaFile: false,
    suffix: 'profile',
    xmlName: 'Profile',
    xmlTag: undefined,
    pruneOnly: true,
  },
  // NOTE: CustomObjectTranslation pruneOnly entry is added in metadataManager
  // after the merge to avoid xmlName collision with the fieldTranslation entry above.
  {
    directoryName: 'translations',
    inFolder: false,
    metaFile: false,
    suffix: 'translation',
    xmlName: 'Translations',
    xmlTag: undefined,
    pruneOnly: true,
  },

  // Profile children - SDR doesn't define these, needed for granular diff
  {
    inFolder: false,
    metaFile: false,
    parentXmlName: 'Profile',
    xmlName: 'ProfileApplicationVisibility',
    xmlTag: 'applicationVisibilities',
    key: 'application',
    excluded: true,
  },
  {
    inFolder: false,
    metaFile: false,
    parentXmlName: 'Profile',
    xmlName: 'ProfileCategoryGroupVisibility',
    xmlTag: 'categoryGroupVisibilities',
    key: 'dataCategoryGroup',
    excluded: true,
  },
  {
    inFolder: false,
    metaFile: false,
    parentXmlName: 'Profile',
    xmlName: 'ProfileApexClassAccess',
    xmlTag: 'classAccesses',
    key: 'apexClass',
    excluded: true,
  },
  {
    inFolder: false,
    metaFile: false,
    parentXmlName: 'Profile',
    xmlName: 'ProfileCustomMetadataTypeAccess',
    xmlTag: 'customMetadataTypeAccesses',
    key: 'name',
    excluded: true,
  },
  {
    inFolder: false,
    metaFile: false,
    parentXmlName: 'Profile',
    xmlName: 'ProfileCustomPermissions',
    xmlTag: 'customPermissions',
    key: 'name',
    excluded: true,
  },
  {
    inFolder: false,
    metaFile: false,
    parentXmlName: 'Profile',
    xmlName: 'ProfileCustomSettingAccesses',
    xmlTag: 'customSettingAccesses',
    key: 'name',
    excluded: true,
  },
  {
    inFolder: false,
    metaFile: false,
    parentXmlName: 'Profile',
    xmlName: 'ProfileExternalDataSourceAccess',
    xmlTag: 'externalDataSourceAccesses',
    key: 'externalDataSource',
    excluded: true,
  },
  {
    inFolder: false,
    metaFile: false,
    parentXmlName: 'Profile',
    xmlName: 'ProfileFieldLevelSecurity',
    xmlTag: 'fieldPermissions',
    key: 'field',
    excluded: true,
  },
  {
    inFolder: false,
    metaFile: false,
    parentXmlName: 'Profile',
    xmlName: 'ProfileFlowAccess',
    xmlTag: 'flowAccesses',
    key: 'flow',
    excluded: true,
  },
  {
    inFolder: false,
    metaFile: false,
    parentXmlName: 'Profile',
    xmlName: 'ProfileLoginFlow',
    xmlTag: 'loginFlows',
    key: 'friendlyname',
    excluded: true,
  },
  {
    inFolder: false,
    metaFile: false,
    parentXmlName: 'Profile',
    xmlName: 'ProfileLayoutAssignments',
    xmlTag: 'layoutAssignments',
    key: '<object>',
    excluded: true,
  },
  {
    inFolder: false,
    metaFile: false,
    parentXmlName: 'Profile',
    xmlName: 'ProfileLoginHours',
    xmlTag: 'loginHours',
    key: '<array>',
    excluded: true,
  },
  {
    inFolder: false,
    metaFile: false,
    parentXmlName: 'Profile',
    xmlName: 'ProfileLoginIpRange',
    xmlTag: 'loginIpRanges',
    key: '<array>',
    excluded: true,
  },
  {
    inFolder: false,
    metaFile: false,
    parentXmlName: 'Profile',
    xmlName: 'ProfileObjectPermissions',
    xmlTag: 'objectPermissions',
    key: 'object',
    excluded: true,
  },
  {
    inFolder: false,
    metaFile: false,
    parentXmlName: 'Profile',
    xmlName: 'ProfileApexPageAccess',
    xmlTag: 'pageAccesses',
    key: 'apexPage',
    excluded: true,
  },
  {
    inFolder: false,
    metaFile: false,
    parentXmlName: 'Profile',
    xmlName: 'ProfileActionOverride',
    xmlTag: 'profileActionOverrides',
    key: 'actionName',
    excluded: true,
  },
  {
    inFolder: false,
    metaFile: false,
    parentXmlName: 'Profile',
    xmlName: 'ProfileRecordTypeVisibility',
    xmlTag: 'recordTypeVisibilities',
    key: 'recordType',
    excluded: true,
  },
  {
    inFolder: false,
    metaFile: false,
    parentXmlName: 'Profile',
    xmlName: 'ProfileTabVisibility',
    xmlTag: 'tabVisibilities',
    key: 'tab',
    excluded: true,
  },
  {
    inFolder: false,
    metaFile: false,
    parentXmlName: 'Profile',
    xmlName: 'ProfileUserPermission',
    xmlTag: 'userPermissions',
    key: 'name',
    excluded: true,
  },

  // Translations children - SDR doesn't define these, needed for granular diff
  {
    inFolder: false,
    metaFile: false,
    parentXmlName: 'Translations',
    xmlName: 'BotTranslation',
    xmlTag: 'bots',
    key: 'fullName',
    excluded: true,
  },
  {
    inFolder: false,
    metaFile: false,
    parentXmlName: 'Translations',
    xmlName: 'CustomApplicationTranslation',
    xmlTag: 'customApplications',
    key: 'name',
    excluded: true,
  },
  {
    inFolder: false,
    metaFile: false,
    parentXmlName: 'Translations',
    xmlName: 'CustomLabelTranslation',
    xmlTag: 'customLabels',
    key: 'name',
    excluded: true,
  },
  {
    inFolder: false,
    metaFile: false,
    parentXmlName: 'Translations',
    xmlName: 'CustomPageWebLinkTranslation',
    xmlTag: 'customPageWebLinks',
    key: 'name',
    excluded: true,
  },
  {
    inFolder: false,
    metaFile: false,
    parentXmlName: 'Translations',
    xmlName: 'CustomTabTranslation',
    xmlTag: 'customTabs',
    key: 'name',
    excluded: true,
  },
  {
    inFolder: false,
    metaFile: false,
    parentXmlName: 'Translations',
    xmlName: 'FlowDefinitionTranslation',
    xmlTag: 'flowDefinitions',
    key: 'fullName',
    excluded: true,
  },
  {
    inFolder: false,
    metaFile: false,
    parentXmlName: 'Translations',
    xmlName: 'PipelineInspMetricConfigTranslation',
    xmlTag: 'pipelineInspMetricConfigs',
    key: 'name',
    excluded: true,
  },
  {
    inFolder: false,
    metaFile: false,
    parentXmlName: 'Translations',
    xmlName: 'PromptTranslation',
    xmlTag: 'prompts',
    key: 'name',
    excluded: true,
  },
  {
    inFolder: false,
    metaFile: false,
    parentXmlName: 'Translations',
    xmlName: 'GlobalQuickActionTranslation',
    xmlTag: 'quickActions',
    key: 'name',
    excluded: true,
  },
  {
    inFolder: false,
    metaFile: false,
    parentXmlName: 'Translations',
    xmlName: 'ReportTypeTranslation',
    xmlTag: 'reportTypes',
    key: 'name',
    excluded: true,
  },
  {
    inFolder: false,
    metaFile: false,
    parentXmlName: 'Translations',
    xmlName: 'ScontrolTranslation',
    xmlTag: 'scontrols',
    key: 'name',
    excluded: true,
  },

  {
    directoryName: 'bots',
    inFolder: false,
    metaFile: true,
    xmlName: 'VirtualBot',
    content: [
      {
        suffix: 'bot',
        xmlName: 'Bot',
      },
      {
        suffix: 'botVersion',
        xmlName: 'BotVersion',
      },
    ],
  },
  {
    xmlName: 'ValueTranslation',
    suffix: 'valueTranslation',
    directoryName: 'none',
    inFolder: false,
    metaFile: false,
    parentXmlName: 'GlobalValueSetTranslation',
    xmlTag: 'valueTranslation',
    excluded: true,
  },
  {
    directoryName: 'discovery',
    inFolder: false,
    metaFile: true,
    xmlName: 'VirtualDiscovery',
    content: [
      {
        suffix: 'model',
        xmlName: 'DiscoveryAIModel',
      },
      {
        suffix: 'goal',
        xmlName: 'DiscoveryGoal',
      },
    ],
  },
  {
    directoryName: 'moderation',
    inFolder: false,
    metaFile: true,
    xmlName: 'VirtualModeration',
    content: [
      {
        suffix: 'keywords',
        xmlName: 'KeywordList',
      },
      {
        suffix: 'rule',
        xmlName: 'ModerationRule',
      },
    ],
  },
  {
    directoryName: 'wave',
    inFolder: false,
    metaFile: true,
    xmlName: 'VirtualWave',
    content: [
      {
        suffix: 'wapp',
        xmlName: 'WaveApplication',
      },
      {
        suffix: 'wcomp',
        xmlName: 'WaveComponent',
      },
      {
        suffix: 'wdf',
        xmlName: 'WaveDataflow',
      },
      {
        suffix: 'wdash',
        xmlName: 'WaveDashboard',
      },
      {
        suffix: 'wds',
        xmlName: 'WaveDataset',
      },
      {
        suffix: 'wlens',
        xmlName: 'WaveLens',
      },
      {
        suffix: 'wtemplate',
        xmlName: 'WaveTemplateBundle',
      },
      {
        suffix: 'wdpr',
        xmlName: 'WaveRecipe',
      },
      {
        suffix: 'xmd',
        xmlName: 'WaveXmd',
      },
    ],
  },
] as Metadata[]
