const METAFILE_SUFFIX: string = '-meta.xml'
const META_REGEX = new RegExp(`${METAFILE_SUFFIX}$`)
const OBJECT_META_XML_SUFFIX = `object${METAFILE_SUFFIX}`
const MASTER_DETAIL_TAG = '<type>MasterDetail</type>'
const FIELD_DIRECTORY_NAME = 'fields'
const LABEL_EXTENSION: string = 'labels'
const LABEL_DIRECTORY_NAME = `labels.${LABEL_EXTENSION}`
const OBJECT_TRANSLATION_META_XML_SUFFIX = `objectTranslation${METAFILE_SUFFIX}`
const INFOLDER_SUFFIX = `Folder`
const WAVE_SUB_TYPES_PREFIX = 'Wave'

export {
  METAFILE_SUFFIX,
  META_REGEX,
  OBJECT_META_XML_SUFFIX,
  MASTER_DETAIL_TAG,
  FIELD_DIRECTORY_NAME,
  LABEL_EXTENSION,
  LABEL_DIRECTORY_NAME,
  OBJECT_TRANSLATION_META_XML_SUFFIX,
  INFOLDER_SUFFIX,
  WAVE_SUB_TYPES_PREFIX,
}
