---
name: NPM Service

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  publish:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    outputs:
      channel: ${{ steps.publish.outputs.channel }}
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          registry-url: "https://registry.npmjs.org"
      - run: npm install -g npm@latest
      - uses: ./.github/actions/install

      - name: Publish
        id: publish
        env:
          RELEASE_TAG: ${{ github.event.release.tag_name }}
        run: |
          npm publish --provenance --access public --tag "latest-rc"
          echo "channel=sfdx-git-delta@$RELEASE_TAG" >> "$GITHUB_OUTPUT"

  e2e-tests:
    needs: [publish]
    uses: ./.github/workflows/run-e2e-tests.yml
    with:
      channel: ${{ needs.publish.outputs.channel }}
