---
name: Main

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "img/**"

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit

  prepare-release:
    needs: [build]
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: googleapis/release-please-action@v5
        id: release
        with:
          token: ${{ secrets.RELEASE_PAT }}
          release-type: node

  perf:
    needs: [prepare-release]
    if: ${{ needs.prepare-release.outputs.release_created != 'true' }}
    uses: ./.github/workflows/reusable-perf.yml
    secrets: inherit
    with:
      auto-push: true
