name: Rollback

on:
  workflow_dispatch:
    inputs:
      version:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org/

      - name: Rollback version
        run: yarn npm tag add "sfdx-git-delta@${{ github.event.inputs.version }}" latest 
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}